### PR TITLE
Cart page

### PR DESCRIPTION
**Pull request by himadri2110**
- In Product & Wishlist Page:
    - Add Item to Cart 
    - Already added item shows ‘Go to Cart’ and navigates to Cart

- In Cart page:
    - Increase and decrease the quantity
    - Remove an item from Cart
    - Move an item from Cart to Wishlist
    - Price calculation (with the final price, discount, and delivery charges)
    - Number of items in Cart
    - Utility functions for Price calculations
    - API calls are placed in the services folder

Test Credentials for login:
email: adarshbalika@gmail.com
password: adarshbalika

### CODE REVIEW

**Review by gopalbbharadva — APPROVED** [review]
Nice UI, 
suggestion: One UX suggestion, You can put a button on **empty**  wishlist and cart  to navigate to product listing.

**Review by tanveertkd — APPROVED** [review]
Just a small suggestion. Instead of showing badges with 0 items for cart and wishlist, you can toggle them when there are items present. Otherwise just hide them altogether.
Apart from that, this is good to go! 👍

**Comment by himadri2110** [comment]
> 

Done, thank you!

**Comment by himadri2110** [comment]
> Just a small suggestion. Instead of showing badges with 0 items for cart and wishlist, you can toggle them when there are items present. Otherwise just hide them altogether. Apart from that, this is good to go! 👍

Makes sense! Done, thank you.

**Comment by himadri2110** [comment]
> Nice UI, suggestion: One UX suggestion, You can put a button on **empty** wishlist and cart to navigate to product listing.

Done, thank you.

**Pull request merged**
